# Generated by Django 5.0.14 on 2026-07-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='okj_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text="Numerical OKJ raqami (m-n: 10492). Lexicographical saralash xavfini yo'qotish uchun alohida saqlanadi. okj_id = f'OKJ-{okj_number}' bilan sinxron bo'ladi.", null=True, unique=True),
        ),
    ]
