# Generated by Django 5.0.14 on 2026-07-02 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Layki',
                'verbose_name_plural': 'Post Layklari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('collection_name', models.CharField(default='Asosiy', help_text="Instagram to'plamlar (papka) nomi", max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saqlangan Post (Bookmark)',
                'verbose_name_plural': 'Saqlangan Postlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'post', 'is_deleted'], name='idx_bm_user_post'), models.Index(fields=['user', '-created_at'], name='idx_bm_user_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='postbookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'post'), name='unique_active_post_bookmark'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', 'post', 'is_deleted'], name='idx_like_user_post'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', '-created_at'], name='idx_like_post_time'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'post'), name='unique_active_post_like'),
        ),
    ]
