# Generated by Django 5.0.14 on 2026-07-02 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_okj_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModerationFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='moderation_flag', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_shadow_banned', models.BooleanField(db_index=True, default=False)),
                ('shadow_banned_at', models.DateTimeField(blank=True, null=True)),
                ('shadow_banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitobxon Moderatsiya Flagi',
                'verbose_name_plural': 'Kitobxon Moderatsiya Flaglari',
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Izoh'), ('BOOK', 'Kitob')], db_index=True, max_length=20)),
                ('target_id', models.UUIDField(db_index=True, help_text='Shikoyat qilinayotgan kontent IDsi')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam yoki reklama'), ('HARASSMENT', 'Haqorat yoki shilqimlik'), ('COPYRIGHT', 'Mualliflik huquqini buzish'), ('INAPPROPRIATE', 'Nomos kontent')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Tekshirilmoqda'), ('RESOLVED', 'Hal qilingan'), ('DISMISSED', 'Rad etilgan')], db_index=True, default='PENDING', max_length=20)),
                ('moderator_notes', models.TextField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kontent Shikoyati',
                'verbose_name_plural': 'Kontent Shikoyatlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'status', '-created_at'], name='idx_mod_queue_tree')],
            },
        ),
    ]
