# Generated by Django 5.0.14 on 2026-07-02 04:44

import comments.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(help_text='Izoh matni (maksimal 1000 belgi)', max_length=1000, validators=[comments.validators.validate_comment_text])),
                ('is_approved', models.BooleanField(default=True, help_text="Moderatsiyadan o'tganligi")),
                ('parent', models.ForeignKey(blank=True, help_text="Ota izoh (Agar null bo'lsa - Root Comment / Asosiy izoh)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['post', 'parent', 'is_deleted', 'is_approved'], name='idx_comment_post_tree'), models.Index(fields=['user', '-created_at'], name='idx_comment_user_time')],
            },
        ),
    ]
