# Generated by Django 5.0.14 on 2026-07-02 04:44

import books.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('isbn_10', models.CharField(blank=True, db_index=True, max_length=13, null=True, validators=[books.validators.validate_isbn_10])),
                ('isbn_13', models.CharField(blank=True, db_index=True, max_length=17, null=True, validators=[books.validators.validate_isbn_13])),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('original_title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[books.validators.validate_publication_year])),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, validators=[books.validators.validate_cover_image_url_or_extension])),
                ('search_keywords', models.CharField(blank=True, help_text="Tezkor qidiruv so'zlari", max_length=500)),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('reading_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('DRAFT', "Qoralama (Foydalanuvchi qo'shgan)"), ('VERIFIED', 'Tasdiqlangan (Kurator tekshirgan)'), ('REJECTED', 'Rad etilgan'), ('ARCHIVED', 'Arxivlangan')], db_index=True, default='DRAFT', max_length=20)),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='m-n: uz', max_length=10, unique=True)),
                ('name', models.CharField(help_text="m-n: O'zbek tili", max_length=100)),
                ('native_name', models.CharField(help_text="m-n: O'zbekcha", max_length=100)),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('country', models.CharField(default="O'zbekiston", max_length=100)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nashriyot',
                'verbose_name_plural': 'Nashriyotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_deleted'], name='books_autho_name_e3a651_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookStatistics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to='books.book')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('reading_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.FloatField(db_index=True, default=0.0)),
            ],
            options={
                'verbose_name': 'Kitob Statistikasi',
                'verbose_name_plural': 'Kitob Statistikalari',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.author'),
        ),
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_url', models.URLField(max_length=500, validators=[books.validators.validate_cover_image_url_or_extension])),
                ('caption', models.CharField(blank=True, help_text='m-n: Old muqova', max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='books.book')),
            ],
            options={
                'verbose_name': 'Kitob Muqovasi',
                'verbose_name_plural': 'Kitob Muqovalari',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgenres', to='books.genre')),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='books.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.language'),
        ),
        migrations.CreateModel(
            name='BookEdition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edition_name', models.CharField(help_text='m-n: 2-nashr, Qattiq muqovali', max_length=200)),
                ('isbn_13', models.CharField(blank=True, max_length=17, null=True, validators=[books.validators.validate_isbn_13])),
                ('isbn_10', models.CharField(blank=True, max_length=13, null=True, validators=[books.validators.validate_isbn_10])),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='books.book')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.publisher')),
            ],
            options={
                'verbose_name': 'Kitob Nashri',
                'verbose_name_plural': 'Kitob Nashrlari',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publisher'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['verification_status', 'is_deleted', '-average_rating'], name='idx_book_verified_rating'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['verification_status', '-created_at'], name='idx_book_status_created'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('page_count__gte', 1), ('page_count__isnull', True), _connector='OR'), name='check_positive_page_count'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('average_rating__gte', 0.0), ('average_rating__lte', 5.0)), name='check_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn_13__isnull', False), models.Q(('isbn_13', ''), _negated=True)), fields=('isbn_13',), name='unique_isbn_13_not_null'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn_10__isnull', False), models.Q(('isbn_10', ''), _negated=True)), fields=('isbn_10',), name='unique_isbn_10_not_null'),
        ),
    ]
