# Generated by Django 5.0.14 on 2026-07-02 05:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_enable_pg_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_book_search_vector'),
        ),
    ]
