# Generated by Django 5.0.14 on 2026-07-02 04:44

import authentication.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Muvaffaqiyatli'), ('FAILED', 'Xatolik / Muvaffaqiyatsiz')], db_index=True, default='SUCCESS', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirish Tarixi (Audit)',
                'verbose_name_plural': 'Kirish Tarixalari (Audit)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20, validators=[authentication.validators.validate_auth_phone_number])),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Tizimga kirish'), ('REGISTER', "Ro'yxatdan o'tish"), ('PASSWORDLESS', 'Parolsiz kirish')], default='LOGIN', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP Kodi',
                'verbose_name_plural': 'OTP Kodlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'code', 'is_used'], name='authenticat_phone_n_01efc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, help_text='Noyob qurilma identifikatori', max_length=255)),
                ('device_type', models.CharField(choices=[('IOS', 'iOS (iPhone/iPad)'), ('ANDROID', 'Android'), ('WEB', 'Web Browser')], default='WEB', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text='m-n: iPhone 15 Pro', max_length=255)),
                ('fcm_token', models.CharField(blank=True, help_text='Push bildirishnoma tokeni', max_length=500)),
                ('refresh_token_jti', models.CharField(blank=True, db_index=True, help_text='Joriy Refresh token ID', max_length=255)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qurilma / Seans',
                'verbose_name_plural': 'Qurilmalar va Seanslar',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='unique_user_device'),
        ),
    ]
