# Generated by Django 5.0.14 on 2026-07-02 04:44

import django.db.models.deletion
import posts.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('QUOTE', 'Iqtibos'), ('REVIEW', 'Kitob taqrizi'), ('SHOWCASE', "Ko'rgazma (Rasm)"), ('EXCHANGE', 'Kitob almashish'), ('GIFT', "Kitob sovg'a qilish"), ('SELL', 'Kitob sotish')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('PUBLISHED', 'Chop etilgan'), ('SCHEDULED', 'Rejalashtirilgan'), ('ARCHIVED', 'Arxivlangan')], db_index=True, default='DRAFT', max_length=20)),
                ('moderation_status', models.CharField(choices=[('PENDING', 'Tekshirilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], db_index=True, default='APPROVED', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Barchaga ochiq'), ('FOLLOWERS_ONLY', 'Faqat obunachilarga'), ('PRIVATE', "Faqat o'zimga")], default='PUBLIC', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, help_text='Asosiy matn / taqriz')),
                ('quote_text', models.TextField(blank=True, help_text='Iqtibos matni')),
                ('quote_page', models.PositiveIntegerField(blank=True, help_text='Kitobning nechanchi betidan', null=True)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[posts.validators.validate_review_rating])),
                ('hashtags', models.CharField(blank=True, help_text='m-n: #uzbekistan #kitob #navoiy', max_length=500)),
                ('mentions', models.CharField(blank=True, help_text='m-n: @bobur @azizillo', max_length=500)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Rejalashtirilgan vaqt', null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='books.book')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='accounts.district')),
                ('library_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='library.libraryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostViewCounter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='view_counter', serialize=False, to='posts.post')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Post Ko'rishlar Hisoblagichi",
                'verbose_name_plural': "Post Ko'rishlar Hisoblagichlari",
            },
        ),
        migrations.CreateModel(
            name='DraftPost',
            fields=[
            ],
            options={
                'verbose_name': 'Qoralama Post',
                'verbose_name_plural': 'Qoralama Postlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, validators=[posts.validators.validate_media_order])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post Rasmi (Media)',
                'verbose_name_plural': 'Post Rasmlari',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(help_text='Shikoyat sababi', max_length=255)),
                ('details', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shikoyat (Report)',
                'verbose_name_plural': 'Shikoyatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'moderation_status', 'is_deleted', '-published_at'], name='idx_post_feed'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'post_type', '-created_at'], name='idx_post_user_type'),
        ),
    ]
