# Generated by Django 5.0.14 on 2026-07-02 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('LIKE', 'Layk bosildi'), ('COMMENT', 'Izoh qoldirildi'), ('FOLLOW', 'Yangi obunachi'), ('READING_GOAL', "O'qish chaqirig'i yutuqlari"), ('SYSTEM', 'Tizim xabari')], default='SYSTEM', max_length=50)),
                ('target_id', models.UUIDField(blank=True, help_text='Tegishli resurs IDsi, masalan post_id yoki comment_id', null=True)),
                ('text', models.TextField(help_text='Bildirishnoma matni')),
                ('is_read', models.BooleanField(default=False, help_text="O'qilganlik holati")),
                ('read_at', models.DateTimeField(blank=True, help_text="O'qilgan vaqt", null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Hodisani amalga oshirgan shaxs (tizim xabarida null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'is_deleted', '-created_at'], name='idx_notif_inbox')],
            },
        ),
    ]
